# Exercises dataframes

In [153]:
#Import the necessary packages
import pandas as pd

## 1. Soccer

Create a Pandas dataframe containing the `soccer_data`. Every list contains following data: 
- Player name
- Position
- Club
- Goals scored
- Age

Give the columns of the DataFrame appropriate names.

In [154]:
soccer_data = [
    ['Lionel Messi', 'Forward', 'Inter Miami', 30, 12],
    ['Cristiano Ronaldo', 'Forward', 'Al Nassr', 25, 10],
    ['Neymar Jr', 'Forward', 'Al Hilal', 20, 18],
    ['Kylian Mbappe', 'Forward', 'PSG', 35, 15],
    ['Kevin De Bruyne', 'Midfielder', 'Manchester City', 15, 20],
    ['Mohamed Salah', 'Forward', 'Liverpool', 28, 14],
    ['Robert Lewandowski', 'Forward', 'Barcelona', 33, 9],
    ['Karim Benzema', 'Forward', 'Real Madrid', 27, 11],
    ['Luka Modric', 'Midfielder', 'Real Madrid', 10, 22],
    ['Erling Haaland', 'Forward', 'Manchester City', 40, 8]
]
df = pd.DataFrame(soccer_data)
df

                    0           1                2   3   4
0        Lionel Messi     Forward      Inter Miami  30  12
1   Cristiano Ronaldo     Forward         Al Nassr  25  10
2           Neymar Jr     Forward         Al Hilal  20  18
3       Kylian Mbappe     Forward              PSG  35  15
4     Kevin De Bruyne  Midfielder  Manchester City  15  20
5       Mohamed Salah     Forward        Liverpool  28  14
6  Robert Lewandowski     Forward        Barcelona  33   9
7       Karim Benzema     Forward      Real Madrid  27  11
8         Luka Modric  Midfielder      Real Madrid  10  22
9      Erling Haaland     Forward  Manchester City  40   8

In [155]:
# Create dataframe
df.columns = ["Name", "position", "Club", "Goal scored", "Age"]
df

                 Name    position             Club  Goal scored  Age
0        Lionel Messi     Forward      Inter Miami           30   12
1   Cristiano Ronaldo     Forward         Al Nassr           25   10
2           Neymar Jr     Forward         Al Hilal           20   18
3       Kylian Mbappe     Forward              PSG           35   15
4     Kevin De Bruyne  Midfielder  Manchester City           15   20
5       Mohamed Salah     Forward        Liverpool           28   14
6  Robert Lewandowski     Forward        Barcelona           33    9
7       Karim Benzema     Forward      Real Madrid           27   11
8         Luka Modric  Midfielder      Real Madrid           10   22
9      Erling Haaland     Forward  Manchester City           40    8

**Renaming column** \
It seems, we made a mistake. Lionel Messi isn't 12 years old and Kevin De Bruyne isn't 20 either. \
Change the last column's name to "Assists" instead of "Age". Ensure the dataframe itself is affected.

In [156]:
# Renaming column
df.rename(columns={"Age": "Assists"}, inplace=True)
df

                 Name    position             Club  Goal scored  Assists
0        Lionel Messi     Forward      Inter Miami           30       12
1   Cristiano Ronaldo     Forward         Al Nassr           25       10
2           Neymar Jr     Forward         Al Hilal           20       18
3       Kylian Mbappe     Forward              PSG           35       15
4     Kevin De Bruyne  Midfielder  Manchester City           15       20
5       Mohamed Salah     Forward        Liverpool           28       14
6  Robert Lewandowski     Forward        Barcelona           33        9
7       Karim Benzema     Forward      Real Madrid           27       11
8         Luka Modric  Midfielder      Real Madrid           10       22
9      Erling Haaland     Forward  Manchester City           40        8

**Change the index labels** to player1, player2 etc.

In [157]:
# Index labels
df.index = [
    "p1", "p2", "p3", "p4", "p5",
    "p6", "p7", "p8", "p9", "p10"
]
df

                   Name    position             Club  Goal scored  Assists
p1         Lionel Messi     Forward      Inter Miami           30       12
p2    Cristiano Ronaldo     Forward         Al Nassr           25       10
p3            Neymar Jr     Forward         Al Hilal           20       18
p4        Kylian Mbappe     Forward              PSG           35       15
p5      Kevin De Bruyne  Midfielder  Manchester City           15       20
p6        Mohamed Salah     Forward        Liverpool           28       14
p7   Robert Lewandowski     Forward        Barcelona           33        9
p8        Karim Benzema     Forward      Real Madrid           27       11
p9          Luka Modric  Midfielder      Real Madrid           10       22
p10      Erling Haaland     Forward  Manchester City           40        8

## 2. More soccer

This time, the soccer data is stored in a dictionary containing lists. The values of the dictionary, are lists containing the data of a column, the keys are the column names. Create a dataframe using the `soccer_data` below.

In [158]:
soccer_data = {
    'Player Name': [
        'Lionel Messi', 'Cristiano Ronaldo', 'Neymar Jr', 'Kylian Mbappe', 'Kevin De Bruyne', 
        'Mohamed Salah', 'Robert Lewandowski', 'Karim Benzema', 'Luka Modric', 'Erling Haaland'
    ],
    'Player Number': [10, 7, 11, 9, 17, 12, 8, 19, 3, 2],
    'Position': [
        'Forward', 'Forward', 'Forward', 'Forward', 'Midfielder', 
        'Forward', 'Forward', 'Forward', 'Midfielder', 'Forward'
    ],
    'Club': [
        'Inter Miami', 'Al Nassr', 'Al Hilal', 'PSG', 'Manchester City', 
        'Liverpool', 'Barcelona', 'Real Madrid', 'Real Madrid', 'Manchester City'
    ],
    'Goals Scored (Season)': [30, 25, 20, 35, 15, 28, 33, 27, 10, 40],
    'Assists (Season)': [12, 10, 18, 15, 20, 14, 9, 11, 22, 8]
}

In [159]:
# Create DataFrame
df = pd.DataFrame(soccer_data)
df

,Player Name,Player Number,Position,Club,Goals Scored (Season),Assists (Season)
0,Lionel Messi,10,Forward,Inter Miami,30,12
1,Cristiano Ronaldo,7,Forward,Al Nassr,25,10
2,Neymar Jr,11,Forward,Al Hilal,20,18
3,Kylian Mbappe,9,Forward,PSG,35,15
4,Kevin De Bruyne,17,Midfielder,Manchester City,15,20
5,Mohamed Salah,12,Forward,Liverpool,28,14
6,Robert Lewandowski,8,Forward,Barcelona,33,9
7,Karim Benzema,19,Forward,Real Madrid,27,11
8,Luka Modric,3,Midfielder,Real Madrid,10,22
9,Erling Haaland,2,Forward,Manchester City,40,8

You see we have an extra column `Player Number` containing the player's shirt numbers. Use this data to set the index labels. Doing so, you see two dark grey rows on top containing names. Remove the index column name.

❓ Is it a good idea to use the players's numbers as index labels? Why (not)?

In [160]:
# Index labels
df.set_index("Player Number", inplace=True)

df.index.name = None                 # remove index column name
df

,Player Name,Position,Club,Goals Scored (Season),Assists (Season)
10,Lionel Messi,Forward,Inter Miami,30,12
7,Cristiano Ronaldo,Forward,Al Nassr,25,10
11,Neymar Jr,Forward,Al Hilal,20,18
9,Kylian Mbappe,Forward,PSG,35,15
17,Kevin De Bruyne,Midfielder,Manchester City,15,20
12,Mohamed Salah,Forward,Liverpool,28,14
8,Robert Lewandowski,Forward,Barcelona,33,9
19,Karim Benzema,Forward,Real Madrid,27,11
3,Luka Modric,Midfielder,Real Madrid,10,22
2,Erling Haaland,Forward,Manchester City,40,8

**Indexing** 
- Display the club of Kevin De Bruyne
- Change the club of Kevin De Bruyne to "Red Devils"
- Display the Player Name column
- Display the data of the player with shirt number 7, using both integer and label position

In [161]:
#Indexing
df.loc[df["Player Name"] == "Kevin De Bruyne", "Club"].iloc[0]
df.loc[df["Player Name"] == "Kevin De Bruyne", "Club"] = "Red Devils"
df["Player Name"]
df[df.index == 7].iloc[0]

Player Name              Cristiano Ronaldo
Position                           Forward
Club                              Al Nassr
Goals Scored (Season)                   25
Assists (Season)                        10
Name: 7, dtype: object

**Slicing** 
- Display the players with shirt number 10, 7 and 11 using both integer and label position
- Display the players with at least 10 assists
- Display all midfield players
- Display the Player Name, Position and Club of Karim, Luka and Erling

In [162]:
#Slicing
df.loc[[10, 7, 11]]
df[df["Assists (Season)"] >= 10]
df[df["Position"] == "Midfielder"]
df[df["Player Name"].isin(["Karim Benzema", "Luka Modric", "Erling Haaland"])][
    ["Player Name", "Position", "Club"]]

       Player Name    Position             Club
19   Karim Benzema     Forward      Real Madrid
3      Luka Modric  Midfielder      Real Madrid
2   Erling Haaland     Forward  Manchester City


## 3. Employees
In this lab exercise, you will explore a dataset containing information about employees in a company using Pandas. You will perform various data manipulation and analysis tasks to gain insights into the employee data.

**Dataset:**
You are provided with a dictionary `employee_data` containing employee information:

In [163]:
employee_data = {
    'EmployeeID': [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 122, 123, 124, 125, 126, 127, 128, 129, 130
    ],
    'Name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack',
        'Katherine', 'Leo', 'Mia', 'Nathan', 'Olivia', 'Paul', 'Quinn', 'Rachel', 'Samuel', 'Tina',
        'Uma', 'Victor', 'Wendy', 'Xander', 'Yasmine', 'Zack', 'Adam', 'Bella', 'Chris', 'Diana'
    ],
    'Department': [
        'HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR', 'Finance', 'Marketing', 'Sales',
        'IT', 'HR', 'Finance', 'Marketing', 'Sales', 'HR', 'IT', 'Finance', 'Marketing', 'Sales',
        'IT', 'HR', 'Finance', 'Marketing', 'Sales', 'HR', 'IT', 'Finance', 'Marketing', 'Sales'
    ],
    'Salary': [
        60000, 75000, 80000, 70000, 65000, 72000, 68000, 81000, 69000, 66000,
        77000, 64000, 85000, 73000, 67000, 61000, 79000, 82000, 74000, 66000,
        78000, 62000, 83000, 76000, 71000, 63000, 80000, 75000, 87000, 72000
    ]
}
employees = pd.DataFrame(employee_data)
employees

    EmployeeID       Name Department  Salary
0          101      Alice         HR   60000
1          102        Bob         IT   75000
2          103    Charlie    Finance   80000
3          104      David  Marketing   70000
4          105       Emma      Sales   65000
5          106      Frank         IT   72000
6          107      Grace         HR   68000
7          108     Hannah    Finance   81000
8          109        Ian  Marketing   69000
9          110       Jack      Sales   66000
10         111  Katherine         IT   77000
11         112        Leo         HR   64000
12         113        Mia    Finance   85000
13         114     Nathan  Marketing   73000
14         115     Olivia      Sales   67000
15         116       Paul         HR   61000
16         117      Quinn         IT   79000
17         118     Rachel    Finance   82000
18         119     Samuel  Marketing   74000
19         120       Tina      Sales   66000
20         121        Uma         IT   78000
21         122     Victor         HR   62000
22         123      Wendy    Finance   83000
23         124     Xander  Marketing   76000
24         125    Yasmine      Sales   71000
25         126       Zack         HR   63000
26         127       Adam         IT   80000
27         128      Bella    Finance   75000
28         129      Chris  Marketing   87000
29         130      Diana      Sales   72000

**DataFrame Creation:**
- Create a Pandas DataFrame named 'employees' from the provided dictionary 'employee_data'.
- Use their employee number as row index. Remove the row index column name.

**Data Exploration:**
- Display the first 3 rows of the DataFrame to get an overview of the data. 
- Check the summary statistics for the 'Salary' column. 
- Determine the number of employees in each department.

**Data Analysis:**
- Display the min, max, mean and median of the 'Salary' column.
- Identify the employee(s) with the highest salary and their details.
- Determine the department with the lowest average salary.
- Add a new column 'Salary Increase' to the DataFrame, where each employee's salary is increased by 10%.

In [164]:
# Your code
employees.set_index("EmployeeID", inplace=True)
employees.index.name = None
employees.head(3)
employees["Salary"].describe()
employees.groupby("Department")["Name"].count()
employees["Salary"].agg(["min", "max", "mean", "median"])
max_salary = employees["Salary"].max()
employees[employees["Salary"] == max_salary]
dept_avg = employees.groupby("Department")["Salary"].mean()
dept_avg.idxmin()
dept_avg

Department
Finance      81000.000000
HR           63000.000000
IT           76833.333333
Marketing    74833.333333
Sales        67833.333333
Name: Salary, dtype: float64

## 4. Sales data

In [168]:
import numpy as np

sales_data = {
    'Product_ID': list(range(101, 151)),
    'Product_Name': [
        'Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smartwatch', 'Gaming Console', 'Keyboard', 'Mouse', 
        'Monitor', 'Printer', 'Speaker', 'Camera', 'External Hard Drive', 'Router', 'Microphone',
        'Smart TV', 'Projector', 'Power Bank', 'VR Headset', 'Graphics Card', 'Processor', 'RAM', 
        'Motherboard', 'SSD', 'HDD', 'USB Flash Drive', 'Cooling Pad', 'Tripod', 'Streaming Device', 
        'E-Reader', 'Wireless Charger', 'Portable Speaker', 'Game Controller', 'Webcam', 'Smart Light', 
        'Smart Doorbell', 'Fitness Band', 'Drone', 'Bluetooth Adapter', 'Drawing Tablet', 'Coffee Maker', 
        'Air Purifier', 'Robot Vacuum', 'Electric Kettle', 'Blender', 'Toaster', 'Smart Refrigerator', 
        'Washing Machine', 'Oven', 'Microwave'
    ],
    'Category': [
        'Electronics', 'Electronics', 'Electronics', 'Accessories', 'Electronics', 'Gaming', 'Accessories', 
        'Accessories', 'Electronics', 'Office Supplies', 'Audio', 'Photography', 'Storage', 'Networking', 
        'Audio', 'Electronics', 'Office Supplies', 'Accessories', 'Gaming', 'Computer Components', 
        'Computer Components', 'Computer Components', 'Computer Components', 'Storage', 'Storage', 
        'Accessories', 'Accessories', 'Photography', 'Streaming', 'Electronics', 'Accessories', 'Audio', 
        'Gaming', 'Accessories', 'Smart Home', 'Smart Home', 'Wearable', 'Drones', 'Accessories', 
        'Accessories', 'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances', 
        'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances', 'Home Appliances'
    ],
    'Price': [
        1200, 800, 400, 100, 300, 500, 50, 40, 250, 150, 200, 700, 120, 90, 60, 1000, 850, 35, 
        600, 400, 300, 150, 200, 180, 130, 20, 45, 100, 120, 250, 75, 220, 55, 90, 200, 180, 
        150, 300, 110, 150, 180, 220, 100, 120, 400, 500, 450, 350, 320
    ],
    'Quantity_Sold': [
        50, 100, 80, 200, 120, 75, 95, np.nan, 60, 110, 130, 40, np.nan, 85, 90, 55, 30, 200, 
        35, np.nan, 65, 45, 100, 70, 85, 150, np.nan, 90, 50, 200, 105, 65, 140, 55, 60, 70, 
        np.nan, 30, 45, 90, 35, 60, 95, np.nan, 110, 75, 55, 80, 100
    ],
    'Brand': [
        'Dell', 'Apple', 'Samsung', 'Sony', 'Fitbit', 'Microsoft', 'Logitech', 'HP', 'LG', 'Canon', 
        'JBL', 'Nikon', 'Seagate', 'TP-Link', 'Blue Yeti', 'Samsung', 'Epson', 'Anker', 'Oculus', 
        'NVIDIA', 'Intel', 'Corsair', 'ASUS', 'Kingston', 'Western Digital', 'SanDisk', 'Cooler Master', 
        'Manfrotto', 'Roku', 'Amazon', 'Belkin', 'Bose', 'Xbox', 'Logitech', 'Philips', 'Ring', 
        'Garmin', 'DJI', 'TP-Link', 'Wacom', 'Keurig', 'Dyson', 'iRobot', 'Breville', 'Ninja', 'Cuisinart', 
        'Samsung', 'LG', 'Bosch', 'Panasonic'
    ],
    'Release_Year': [
        2021, 2020, 2019, 2022, 2021, 2020, 2018, 2017, 2019, 2022, 2021, 2020, 2019, 2021, 2018, 
        2022, 2021, 2020, 2023, 2021, 2019, 2020, 2018, 2022, 2023, 2017, 2018, 2019, 2020, 2021, 
        2018, 2019, 2022, 2020, 2021, 2023, 2022, 2018, 2020, 2019, 2021, 2023, 2020, 2022, 2021, 
        2019, 2018, 2020, 2023
    ],
    'Ratings': [
        4.5, 4.7, 4.3, 4.2, 4.6, 4.8, 4.0, np.nan, 4.1, 4.3, 4.6, 4.7, np.nan, 4.5, 4.0, 
        4.4, 4.1, 3.9, 4.9, np.nan, 4.2, 4.0, 4.3, 4.6, 4.8, 4.1, np.nan, 4.5, 4.2, 4.7, 
        4.0, 4.3, 4.1, 4.6, 4.2, 4.8, 4.9, np.nan, 4.0, 4.1, 4.3, 4.6, 4.2, 4.5, np.nan, 
        4.7, 4.3, 4.2, 4.8
    ]
}

**DataFrame Creation:**
- Create a Pandas DataFrame named 'sales' from the provided dictionary 'sales_data'.
    <details>
    <summary> error? </summary>
    When trying to create a DataFrame, you get an error. The values of the dictionary are not of equal length... Meaning, the last entry/entries is/are incomplete. Omit these entries to create the DataFrame.
    </details>

- Use the Product ID's as index and remove the index heading.
- Set all NaN values in the "Quantity_Sold" column to 0.
- Delete rows containing NaN values except if they only occur in the ratings column. Check the documentation of the known method to delete rows containing NaN's. 
- Show the first 5 rows (without using slicing) and display information about the DataFrame.
- Show the dimensions of the DataFrame

**Indexing and Slicing:**
- Access the last 2 rows and the 'Product_Name' and 'Price' columns using both label-based and positional-based indexing.
- Extract the data for products with product id's 105 to 118 and all columns using integer-based indexing.
    - Don't start counting the rows. It might be useful to reset de indices back to position integers. We still want to keep the Product_ID in our DataFrame, make a new column for this data with an appropriate name.
- **Boolean filtering:** Filter the data to include only products priced below 100.

In [166]:
# Your code

### 4. Sales data part 2

* Read in the additional sales data, stored in the csv file "sales_data.csv" and create a new DataFrame.
* Inspect the file before reading in the data!
* Combine the first sales DataFrame with this new DataFrame in a DataFrame `all_sales`. Ensure both DataFrames are combined correctly. The resulting DataFrame should be of shape 149x8.
* Sort the data from eldest to newest
* Reset the indices to their integer positions, without adding an extra column with the current index label
* Write the resulting DataFrame to a new csv file "all_sales.csv".

In [167]:
# Sales data part 2

# Your code

#### About the dataset

Did you notice something odd?
<details>
  <summary>No</summary>
  Take a closer look!
</details>

<details>
  <summary>Yes</summary>
  An Electric Kettle in the category Photography? An Apple Blender in the category Audio? This seems rather odd. We have to admit, we asked ChatGPT to generate 100 additional entries of sample data in 'csv' format. Surprisingly we got a generated csv as response, easy peasy right? Yes but no...

  ChatGPT knew some context (programming in Python) when generating the csv. Let's take a look at the analysis of the reasoning of ChatGPT. What do you see?

  ![GenAI analysis reasoning](analysis.png)

  The dataset is generated using Python code and relies on numpy random. Therefore, there is no correlation between the Product, Product ID, Category, Brand etc. 

  The moral of the story: GenAI results might seem good or qualitative, but take a closer look, be sceptic and check out the reasoning to confirm the quality.


</details>